### ISSUE TITLE
Obligation extraction bug

### ISSUE THREAD

**Issue by ML44** [TLAPS/v2-tlapm#2]
Obligation extraction assumes previous lemma instead of giving definition.

```
CONSTANT a,b,c

S == {a,b,c}

LEMMA \A x \in {a,b,c} : \E x0 \in {a,b,c} : x # x0 OBVIOUS

LEMMA \A x \in S : \E x0 \in S : x # x0 OBVIOUS

LEMMA \A x \in S : \E x0 \in S : x # x0 BY DEF S

LEMMA \A x \in {a,b,c} : \E x0 \in {b,c,a} : x # x0 BY DEF S
```

**Comment by quicquid** [comment]
Just a remark: none of the lemmas should be provable, since they have a countermodel when the domain contains only one element. The bug is that the extracted obligations have additional assumptions which should not be the case.

**Comment by quicquid** [comment]
I fixed the part where the usable fact was wrongly added, BY fact is still buggy though.
